apiVersion: batch/v1
kind: Job
metadata:
  name: ecr-anywhere-first-setup
spec:
  template:
    metadata:
      name: ecr-anywhere-first-setup
    spec:
      serviceAccountName: svac-ecr-kube-helper
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
      - name: ecr-anywhere-first-setup
        imagePullPolicy: Always
        image: "{{ .Values.job.image.name }}:{{ .Values.job.image.tag }}"
        command:
        - "/bin/sh"
        - "-c"
        - |
          AWS_REGION={{ .Values.ecr.aws_region }}
          mkdir ~/.aws
          printf "[default]\nregion = {{ .Values.ecr.aws_region }}\noutput = json" > ~/.aws/config
          printf "[default]\naws_access_key_id = {{ .Values.ecr.aws_access_key_id }}\naws_secret_access_key = {{ .Values.ecr.aws_secret_access_key }}" > ~/.aws/credentials
          DOCKER_REGISTRY_SERVER=https://{{ .Values.ecr.aws_account }}.dkr.ecr.{{ .Values.ecr.aws_region }}.amazonaws.com
          DOCKER_USER=AWS
          DOCKER_PASSWORD=`aws ecr get-login-password`
          kubectl delete secret {{ .Values.secret.name}} || true
          kubectl create secret docker-registry {{ .Values.secret.name}} --docker-server=${DOCKER_REGISTRY_SERVER} --docker-username=${DOCKER_USER} --docker-password=${DOCKER_PASSWORD}
          echo "Updated ECR token"